### PR TITLE
Style Guide

### PR DESCRIPTION
**Pull request by MWLangenhorst88**
I have the style guide up to standards, but I can still use some feedback on the code itself if anyone's interested!

### CODE REVIEW

**Comment by LukeBillington** [comment]
Documentation and linting works as specified. Might suggest adding documentation of the various input options and what they are within the readme.

**Comment by LukeBillington** [comment]
For some code suggestions, consider looking at JavaScript's error objects. Usage is like: `throw new Error(message)`. This prevents the form from rendering improperly.

Also consider finding a way to combine all output to one string instead of outputting each as console.log. This can make code more reusable. Great work so far otherwise!

**Comment by MWLangenhorst88** [comment]
Added suggestions and added names to checkbox and select tags. Not too sure why I didn't finish that part in the first place!

**Comment by nmcayouette** [comment]
After the implemented updates, LGTM!

**Comment by MWLangenhorst88** [comment]
Thanks, guys!

**Pull request merged**
